services:
  - type: web
    name: my-web-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
  - type: worker
    name: telegram-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python telegram_bot.py"
